### ISSUE TITLE
Linux有Bug！！！

### ISSUE THREAD

**Issue by 1526lk** [Blessing-Studio/WonderLab#19]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题

### 问题描述

发行版：Debian11.6
桌面环境：KDE Plasma
dotnet版本：6.0+7.0SDK
①应用程序菜单里显示名称为test（已解决，在/usr/share/applations里改过来就行）

②最严重的bug，无法启动，根本就是打不开

### 问题复现率

必现

### 复现步骤

每一次都打不开

### 操作系统版本

Linux

### WonderLab版本

1.0.1.4

### 插件信息

无

### 补充信息

找了一下文件路径，疑似大小写问题
但是程序本身也有问题
这是终端的输出
Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl) in /_/src/Avalonia.Visuals/Media/FontManager.cs:line 33
   at Avalonia.Media.FontManager.get_Current() in /_/src/Avalonia.Visuals/Media/FontManager.cs:line 53
   at Avalonia.Media.TextFormatting.TextCharacters.TryGetRunProperties(ReadOnlySlice`1 text, Typeface typeface, Typeface defaultTypeface, Int32& count) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 129
   at Avalonia.Media.TextFormatting.TextCharacters.CreateShapeableRun(ReadOnlySlice`1 text, TextRunProperties defaultProperties) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 62
   at Avalonia.Media.TextFormatting.TextCharacters.GetShapeableCharacters() in /_/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 40
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FetchTextRuns(ITextSource textSource, Int32 firstTextSourceIndex, TextLineBreak previousLineBreak, TextLineBreak& nextLineBreak) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextFormatterImpl.cs:line 280
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextFormatterImpl.cs:line 15
   at Avalonia.Media.TextFormatting.TextLayout.UpdateLayout() in /_/src/Avalonia.Visuals/Media/TextFormatting/TextLayout.cs:line 223
   at Avalonia.Media.TextFormatting.TextLayout..ctor(String text, Typeface typeface, Double fontSize, IBrush foreground, TextAlignment textAlignment, TextWrapping textWrapping, TextTrimming textTrimming, TextDecorationCollection textDecorations, Double maxWidth, Double maxHeight, Double lineHeight, Int32 maxLines, IReadOnlyList`1 textStyleOverrides) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextLayout.cs:line 71
   at FluentAvalonia.UI.Controls.SymbolIcon.GenerateText()
   at FluentAvalonia.UI.Controls.SymbolIcon.OnPropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.AvaloniaObject.OnPropertyChangedCore[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 647
   at Avalonia.Animation.Animatable.OnPropertyChangedCore[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Animation/Animatable.cs:line 169
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 756
   at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 531
   at Avalonia.ValueStore.NotifyValueChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 355
   at Avalonia.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 121
   at Avalonia.AvaloniaObject.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 367
   at FluentAvalonia.UI.Controls.SymbolIcon.set_Symbol(Symbol value)
   at FluentAvalonia.UI.Controls.IconElementConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at WonderLab.Views.MainView.!XamlIlPopulate(IServiceProvider , MainView ) in /home/mailset/Code/WonderLab/WonderLab/Views/MainView.axaml:line 21
   at WonderLab.Views.MainView.!XamlIlPopulateTrampoline(MainView )
   at WonderLab.Views.MainView.InitializeComponent(Boolean loadXaml) in /home/mailset/Code/WonderLab/WonderLab/Avalonia.NameGenerator/Avalonia.NameGenerator.AvaloniaNameSourceGenerator/WonderLab.Views.MainView.g.cs:line 29
   at WonderLab.Views.MainView.InitializeComponent() in /home/mailset/Code/WonderLab/WonderLab/Views/MainView.axaml.cs:line 37
   at WonderLab.Views.MainView..ctor() in /home/mailset/Code/WonderLab/WonderLab/Views/MainView.axaml.cs:line 23
   at WonderLab.MainWindow.InitializeComponent() in /home/mailset/Code/WonderLab/WonderLab/MainWindow.axaml.cs:line 388
   at WonderLab.MainWindow..ctor() in /home/mailset/Code/WonderLab/WonderLab/MainWindow.axaml.cs:line 404
   at WonderLab.App.OnFrameworkInitializationCompleted() in /home/mailset/Code/WonderLab/WonderLab/App.axaml.cs:line 134
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 312
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at WonderLab.Program.Main(String[] args) in /home/mailset/Code/WonderLab/WonderLab/Program.cs:line 42
已放弃

**Comment by hei-shou** [comment]
这个问题已有解决方案，只需要在启动命令前加一个 LC_ALL=C 即可正常运行
