### ISSUE TITLE
macOS 下在家目录中下载闪退

### ISSUE THREAD

**Issue by weitcis** [Blessing-Studio/WonderLab#20]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题

### 问题描述

将MC路径设置在用户家目录下后，使用启动器下载核心会闪退。

### 问题复现率

必现

### 复现步骤

将MC路径设置在用户家目录下后，使用启动器下载核心。

### 操作系统版本

Mac

### WonderLab版本

1.0.1.2

### 补充信息

使用 shell 启动后尝试复现问题会得到以下错误信息：

```
Unhandled exception. System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/Users/weitcis/.config/WonderLab/Temp\WonderLab.Desktop.exe' with working directory '/Users/weitcis'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at WonderLab.ViewModels.DownItemViewModel.ForgeInstall(ModLoaderInformationViewData mlimvd) in /Users/lqc/Desktop/WonderLab-master/WonderLab/ViewModels/DownItemViewModel.cs:line 302
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue)
   at Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(Void* this, Int32 priority, Int32 priorityContainsMeaningfulValue)
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at WonderLab.Program.Main(String[] args) in /Users/lqc/Desktop/WonderLab-master/WonderLab/Program.cs:line 32
fish: Job 1, '/Applications/WonderLab.app/Con…' terminated by signal SIGABRT (Abort)
```

完整错误报告如下：[report.txt](https://github.com/Blessing-Studio/WonderLab/files/10473364/report.txt)

**Comment by hei-shou** [comment]
此问题已修复，在最新的1.0.1.4可以正常下载

**Comment by weitcis** [comment]
> 此问题已修复，在最新的1.0.1.4可以正常下载

二群里的mac版好像还没更新）

**Comment by weitcis** [comment]
@hei-shou 主分支下最新commit仍然可以复现此bug
