### ISSUE TITLE
[BUG] 未设置默认字体导致的异常退出

### ISSUE THREAD

**Issue by Puqns67** [Blessing-Studio/WonderLab#27]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题

### 问题描述

运行后报错

```
Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl)
   at Avalonia.Media.FontManager.get_Current()
   at Avalonia.Media.TextFormatting.TextCharacters.TryGetRunProperties(ReadOnlySlice`1 text, Typeface typeface, Typeface defaultTypeface, Int32& count)
   at Avalonia.Media.TextFormatting.TextCharacters.CreateShapeableRun(ReadOnlySlice`1 text, TextRunProperties defaultProperties)
   at Avalonia.Media.TextFormatting.TextCharacters.GetShapeableCharacters()
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FetchTextRuns(ITextSource textSource, Int32 firstTextSourceIndex, TextLineBreak previousLineBreak, TextLineBreak& nextLineBreak)
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak)
   at Avalonia.Media.TextFormatting.TextLayout.UpdateLayout()
   at Avalonia.Media.TextFormatting.TextLayout..ctor(String text, Typeface typeface, Double fontSize, IBrush foreground, TextAlignment textAlignment, TextWrapping textWrapping, TextTrimming textTrimming, TextDecorationCollection textDecorations, Double maxWidth, Double maxHeight, Double lineHeight, Int32 maxLines, IReadOnlyList`1 textStyleOverrides)
   at FluentAvalonia.UI.Controls.SymbolIcon.GenerateText()
   at FluentAvalonia.UI.Controls.SymbolIcon.OnPropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.AvaloniaObject.OnPropertyChangedCore[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.Animation.Animatable.OnPropertyChangedCore[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.ValueStore.NotifyValueChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority)
   at Avalonia.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority)
   at Avalonia.AvaloniaObject.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority)
   at FluentAvalonia.UI.Controls.SymbolIcon.set_Symbol(Symbol value)
   at FluentAvalonia.UI.Controls.IconElementConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at WonderLab.Views.MainView.!XamlIlPopulate(IServiceProvider , MainView ) in /home/puqns67/Code/WonderLab/WonderLab/Views/MainView.axaml:line 21
   at WonderLab.Views.MainView.!XamlIlPopulateTrampoline(MainView )
   at WonderLab.Views.MainView.InitializeComponent(Boolean loadXaml) in /home/puqns67/Code/WonderLab/WonderLab/Avalonia.NameGenerator/Avalonia.NameGenerator.AvaloniaNameSourceGenerator/WonderLab.Views.MainView.g.cs:line 29
   at WonderLab.Views.MainView.InitializeComponent() in /home/puqns67/Code/WonderLab/WonderLab/Views/MainView.axaml.cs:line 37
   at WonderLab.Views.MainView..ctor() in /home/puqns67/Code/WonderLab/WonderLab/Views/MainView.axaml.cs:line 23
   at WonderLab.MainWindow.InitializeComponent() in /home/puqns67/Code/WonderLab/WonderLab/MainWindow.axaml.cs:line 391
   at WonderLab.MainWindow..ctor() in /home/puqns67/Code/WonderLab/WonderLab/MainWindow.axaml.cs:line 409
   at WonderLab.Program.Main(String[] args) in /home/puqns67/Code/WonderLab/WonderLab/Program.cs:line 41
fish: Job 1, './WonderLab' terminated by signal SIGABRT (Abort)
```

### 问题复现率

必现

### 复现步骤

1. 直接运行主程序

### 操作系统版本

Linux

### WonderLab版本

git: bd9b5485912677fa487c56c51ab52e5f33899dd4
release: [1.0.1.4](https://github.com/Blessing-Studio/WonderLab/releases/tag/1.0.1.4)

两个版本均复现

### 补充信息

OS: ArchLinux

**Comment by hei-shou** [comment]
此问题现已修复
