### ISSUE TITLE
Arch Linux 下无法安装游戏核心

### ISSUE THREAD

**Issue by MCSeekeri** [Blessing-Studio/WonderLab#34]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题
- [X] 查看 [Actions](https://github.com/Blessing-Studio/WonderLab/Actions) 中最新Dev版是否已修复你所遇到的问题

### 问题描述

在 Arch Linux 下可以正常启动程序，但在安装游戏核心时报错。
内核为 6.1.8-zen1-1-zen，桌面环境为 Plasma 5.26.5，使用 Wayland 和 kwin。

### 问题复现率

必现

### 复现步骤

1.拉取WonderLab源代码
2.编译运行程序
3.安装游戏核心。

### 操作系统版本

Linux

### WonderLab版本

a148951dfc83d75bbbaeed09e15836c81d9266fc

### 补充信息

报错日志：
```
System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/home/mcseekeri/.config/WonderLab/Temp/WonderLab.Desktop' with working directory '/home/mcseekeri/Project/WonderLab'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at WonderLab.ViewModels.DownItemViewModel.VanlliaInstall(String Id) in /home/mcseekeri/Project/WonderLab/WonderLab/ViewModels/DownItemViewModel.cs:line 245
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at WonderLab.Program.Main(String[] args) in /home/mcseekeri/Project/WonderLab/WonderLab/Program.cs:line 24
```

**Comment by MCSeekeri** [comment]
66339d45460153c00c25ccb803a678ada8d8c1f4
问题依旧，而且报错日志还是那些。出于安全原因我暂时无法测试以管理员权限运行会如何。

**Comment by JWJUN233233** [comment]
> 66339d45460153c00c25ccb803a678ada8d8c1f4
> 
> 问题依旧，而且报错日志还是那些。出于安全原因我暂时无法测试以管理员权限运行会如何。

issue没有关闭说明还没解决
这个不是我在管 我也不咋会Linux开发

**Comment by JWJUN233233** [comment]
sorry 那么久我才看到 有时间给你弄上
