### ISSUE TITLE
皮肤预览窗口bug

### ISSUE THREAD

**Issue by JWJUN233233** [Blessing-Studio/WonderLab#65]
### ❗ 检查表

- [X] 搜索了已有的 [issues](https://github.com/Blessing-Studio/WonderLab/issues) 列表中是否有相似问题
- [X] 查看 [Releases](https://github.com/Blessing-Studio/WonderLab/releases) 中最新版是否已修复你所遇到的问题
- [X] 查看 [Actions](https://github.com/Blessing-Studio/WonderLab/Actions) 中最新Dev版是否已修复你所遇到的问题

### 问题描述

none

### 日志

System.ArgumentNullException: Value cannot be null.
   at Avalonia.VisualTree.VisualExtensions.GetVisualAncestors(IVisual visual)+MoveNext()
   at Avalonia.Controls.Primitives.OverlayLayer.GetOverlayLayer(IVisual visual)
   at FluentAvalonia.UI.Controls.ContentDialog.FinalCloseDialog()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at WonderLab.Program.Main(String[] args) in /home/runner/work/WonderLab/WonderLab/WonderLab/Program.cs:line 25

### 问题复现率

高偶发

### 复现步骤

进入档案选择中 点击头像打开设置 然后反复点击里面的按键

### 操作系统版本

全平台

### WonderLab版本

actions build

**Comment by JWJUN233233** [comment]
已修复

**Comment by Blessing-Studio** [comment]
你的议题已解决
感谢反馈
[点击这里反馈新问题](https://github.com/Blessing-Studio/WonderLab/issues/new/choose)
